name: build and push image to github container registry

on:
  workflow_call:
    inputs:
      RUNNER_TAG:
        required: false
        type: string
        default: "ubuntu-latest"

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REGISTRY2: quay.io
  REGISTRY3: docker.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG:  0.${{ github.RUN_NUMBER }}.0  #//${{ github.sha }}

  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  REDIS_HOST: localhost
  REDIS_PASSWORD: "password"
  REDIS_PORT: 6379
  REDIS_USERNAME: "user"
  #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  MONGODB_URI: mongodb://root:password@localhost:27017

jobs:
  build-and-push-image:
    name: 🛠️
    runs-on: ${{ inputs.RUNNER_TAG }}

    services:
      redis:
        image: bitnami/redis:latest
        env:
          REDIS_PASSWORD: password
        ports:
          - 6379:6379

    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # - name: Setup Java 17 (GraalVM)
      #   uses: graalvm/setup-graalvm@v1.2.1
      #   with:
      #     version: 'latest'
      #     java-version: '17'
      #     components: 'native-image'
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     set-java-home: 'true'
      #     cache: 'gradle'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'gradle'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build
        run: ./gradlew build

      - name: Upload Jacoco Test Converage Artifact
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: './build/reports/jacoco/test/html/.' # The folder the action should deploy.
        continue-on-error: true

      # Deploy from a branch
      - name: Deploy Coverage to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/reports/jacoco/test/html # The folder the action should deploy.
        continue-on-error: true

      # Deploy using GitHub Actions
      - name: Setup Pages
        uses: actions/configure-pages@v5
        continue-on-error: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        continue-on-error: true


      - name: SonarQube analyze
        if: job.steps.build.status == success() || job.steps.build.status == failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew sonarqube --info
        continue-on-error: true

      - name: Extract metadata (tags, labels) for registry
        id: meta
        uses: docker/metadata-action@master
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY2 }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY3 }}/${{ env.IMAGE_NAME }}

          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}
          labels: |
            org.opencontainers.image.description="${{ github.event.head_commit.message }}"

      - name: Log in to the GHCR Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Login Quay
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY2 }}
          username: ${{ github.actor }}
          password: ${{ secrets.QUAY_TOKEN }}
        continue-on-error: true

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY3 }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: true
        
      - name: Build and Push Image to Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      # - name: Push image
      #   uses: akhilerm/tag-push-action@v2.2.0
      #   with:
      #     src: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     dst: |
      #       ${{ env.REGISTRY2 }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #       ${{ env.REGISTRY2 }}/${{ env.IMAGE_NAME }}:latest
      #       ${{ env.REGISTRY3 }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #       ${{ env.REGISTRY3 }}/${{ env.IMAGE_NAME }}:latest
      #   continue-on-error: true

