name: Quick Checks SonarQube Static Code Analysis

on:
  workflow_call:

  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:   
  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: generate coverages
        run: go test ./... -coverprofile coverage.out
        continue-on-error: true  

#       - uses: sonarsource/sonarqube-scan-action@master
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#       - uses: sonarsource/sonarqube-quality-gate-action@master
#         timeout-minutes: 5
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
